### ISSUE TITLE
Define threshold for line colours

### ISSUE THREAD

**Issue by mietzen** [Samantha-uk/one#14]
**Is your feature request related to a problem? Please describe.**
Most of my 95% connections are drawn yellow and red despite the network working flawless. 

**Describe the solution you'd like**
I would like to have some variable to define the threshold for line colours, e.g.:

```
panel_custom:
      zigzag:
        green_threshold: 150
        yellow_threshold: 100
        red_threshold: 50
```

**Additional context**
When everything is yellow and red it's hard to see when there is a real problem
