### ISSUE TITLE
The zigzag panel is just blank

### ISSUE THREAD

**Issue by TheZoker** [Samantha-uk/one#7]
**Describe the bug**

The zigzag panel is just blank

My config looks like this:
```yaml
panel_custom:
  - name: zigzag
    sidebar_title: Zigzag
    sidebar_icon: mdi:zigbee
    url_path: zigzag
    module_url: /local/zigzag/zigzag-panel.esm.js
    trust_external_script: true
    config:
      who: world
      zigzag:
        plugin-path: "/local/zigzag/plugins"
        plugin-data:
          type: "zha"
        plugin-layout:
          type: "d3"
        plugin-render:
          type: "three" 
```
I also tried `pixi` as render plugin, but same issue.

**To Reproduce**
1. Go to zigzag panel

**Expected behaviour**
Display panel

**Browser console**
![Screenshot_2021 01 17_13h26m18s_007_](https://user-images.githubusercontent.com/1368405/104842876-f78ed000-58c7-11eb-9978-4e805d42ee17.png)

**Screenshots**
Blank panel:
![Screenshot_2021 01 17_13h24m27s_006_](https://user-images.githubusercontent.com/1368405/104842800-6f102f80-58c7-11eb-89e9-cc8fa9c55fbf.png)

The script is loaded:
![Screenshot_2021 01 17_13h23m43s_004_](https://user-images.githubusercontent.com/1368405/104842801-759ea700-58c7-11eb-9d5a-7caee1c0f851.png)

This is what the html element looks like:
![Screenshot_2021 01 17_13h24m14s_005_](https://user-images.githubusercontent.com/1368405/104842806-7fc0a580-58c7-11eb-8b26-d44d9258275a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 88

I also tried firefox, same issue

**Home Assistant:**
- Core: core-2021.1.4
- Supervisor: supervisor-2021.01.4
- OS: 5.10

**Additional context**
none

**Comment by Samantha-uk** [comment]
Very odd!
I would expect at the very least to see more info in the browser console, such as
![image](https://user-images.githubusercontent.com/45871296/104843315-dfb44d80-58c1-11eb-8254-7686edd3d36f.png)

I run OSX but note you're on Windows.
I'll try to fire up a Windows VM on my Proxmox server to see if I can replicate what you are seeing.
Just to check, you are using the latest files from https://github.com/Samantha-uk/one/tree/main/home-assistant/zigzag-panel/zigzag ?

**Comment by DrCoolzic** [comment]
I do not see the PixiJS 5.35.7 info? I have the following
![image](https://user-images.githubusercontent.com/6078364/104843742-830a6000-58cc-11eb-9091-dbec150c8028.png)

**Comment by TheZoker** [comment]
@Samantha-uk Yes these are exactly the files I installed:
![Screenshot_2021 01 17_17h17m46s_008_](https://user-images.githubusercontent.com/1368405/104849038-f8cff500-58e7-11eb-9c63-fa38b5ee8f59.png)

I have no clue, why there are no logs in the console.... 

Is there anything else I can check on my end?

**Comment by Samantha-uk** [comment]
I'm not sure what else you can check just now to be honest.
I'm still building my Windows VM to try to replicate the issue you are seeing.
Could you jump to the Zigzag discord so we can chat more interactively?
https://discord.gg/SF7PnZDj

**Comment by Samantha-uk** [comment]
It took me a while to spot the issue, perhaps my mind was focused on the new 18Tb NAS that arrived a couple of hours ago! 😃 
When I loaded your config in my system, I experienced _exactly_ what you described, which was a good start (_Don't we all hate issues that are hard to reproduce!_)

In the Home Assistant configuration.yaml, it is **vital** that the `name` element reflects the Web Component name of _whatever_ you want to load.  For Zigzag, it's Web Component name is `custom-panel-zigzag`.

By changing your config as follows, it seemed to work OK here. 
**Not working**
``` yaml
panel_custom:
  - name: zigzag
 ...
```
**Working**
``` yaml
panel_custom:
  - name: custom-panel-zigzag
  ...
  ```

Could you try the same change on your system and let me know if the issue is resolved or persists?
